// buildDigestMarkdown — turns aggregated signals into the daily digest
// markdown that lands at <stateDir>/digest-<yyyy-mm-dd>.md.

import type { Signal } from "./types.js";

function isSkipped(s: Signal): boolean {
  return (s as { skipped?: boolean }).skipped === true;
}

export function buildDigestMarkdown(signals: Signal[], todayIso: string, nowIso: string): string {
  const lines: string[] = [];
  const today = todayIso.slice(0, 10);
  lines.push(`# Industry Radar — ${today}`);
  lines.push("");
  lines.push(
    "Daily aggregation of upstream commits + blog/newsletter signal that may affect Joseph's openclaw fork stack.",
  );
  lines.push("");

  // Repos section
  const repoSignals = signals.filter(
    (s) => s.source && s.source !== "gmail" && s.source !== "blogs" && !isSkipped(s),
  );
  let totalSurfaced = 0;
  for (const sig of repoSignals) {
    totalSurfaced += (sig as { surfaced?: number }).surfaced ?? 0;
  }
  lines.push(`## Upstream commits (${totalSurfaced} flagged)`);
  lines.push("");
  for (const sig of repoSignals) {
    if (!sig.ok) {
      lines.push(`- \`${sig.source}\`: ⚠ scan failed — ${(sig as { error?: string }).error ?? ""}`);
      continue;
    }
    const surfaced = (sig as { surfaced?: number }).surfaced ?? 0;
    const total = (sig as { total?: number }).total ?? 0;
    if (surfaced === 0) {
      lines.push(`- \`${sig.source}\`: clean (${total} commits scanned, none flagged)`);
      continue;
    }
    lines.push(`### \`${sig.source}\` — ${surfaced} flagged`);
    const commits = (sig as { commits?: import("./types.js").ScoredCommit[] }).commits ?? [];
    for (const c of commits) {
      const firstLine = (c.commit?.message ?? "").split("\n", 1)[0]?.slice(0, 100) ?? "";
      const author = c.commit?.author?.name ?? "?";
      const date = (c.commit?.author?.date ?? "").slice(0, 10);
      lines.push(
        `- **score=${c._score}** \`${c.sha?.slice(0, 7)}\` ${firstLine} — ${author} (${date}) — [link](${c.html_url})`,
      );
    }
    lines.push("");
  }

  const skipped = signals.filter((s) => isSkipped(s));
  if (skipped.length > 0) {
    lines.push("## Sources skipped (first-ship)");
    for (const s of skipped) {
      lines.push(`- \`${s.source}\`: ${(s as SkippedReason).reason ?? ""}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`Generated by skill-industry-radar at ${nowIso}.`);
  lines.push(
    "Synthesis prompt available at `sources.json#synthesisPrompt` for fleet-voice synthesis (next iteration).",
  );
  return lines.join("\n");
}

interface SkippedReason {
  reason?: string;
}
